# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
title: "Delta Publications"
email: gaurav.chauhan.alc@outlook.com
description: "Discover the best books and authors from India's leading publishing house."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gauravsc-alc.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  books:
    output: true
    permalink: /:collection/:name/
  authors:
    output: true
    permalink: /:collection/:name/
  blogs:
    output: true
    permalink: /:collection/:name/
  news:
    output: true
    permalink: /:collection/:name/

# Ensure proper URL generation
defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
# Environment variable access
env:
  EMAILJS_PUBLIC_KEY: <%= ENV['EMAILJS_PUBLIC_KEY'] %>
  EMAILJS_SERVICE_ID: <%= ENV['EMAILJS_SERVICE_ID'] %>
  EMAILJS_TEMPLATE_ID: <%= ENV['EMAILJS_TEMPLATE_ID'] %>

