name: Build and deploy site to GitHub Pages

on:
  push:
    branches: [ main ]   # change to the branch you author from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby (for Jekyll)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Update Gemfile.lock for current platform
        run: |
          bundle lock --add-platform x86_64-linux
          bundle lock --add-platform ruby
          bundle lock --remove-platform x64-mingw-ucrt || true

      - name: Install dependencies
        run: |
          gem install bundler -v 2.7.1 --no-document || true
          bundle install --jobs 4 --retry 3

      - name: Build site
        run: bundle exec jekyll build --destination _site

      - name: Generate runtime EmailJS config in build output
        env:
          EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
          EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
          EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
        run: |
          mkdir -p _site/js
          cat > _site/js/emailjs-config.js <<EOF
          // Runtime EmailJS configuration generated by CI — do NOT commit secrets to repo.
          window.EMAILJS_CONFIG = {
            PUBLIC_KEY: '${EMAILJS_PUBLIC_KEY}',
            SERVICE_ID: '${EMAILJS_SERVICE_ID}',
            TEMPLATE_ID: '${EMAILJS_TEMPLATE_ID}'
          };
          EOF
          ls -la _site/js/

      # - name: Deploy to GitHub Pages (gh-pages branch)
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./_site
      #     publish_branch: gh-pages
      #     user_name: "github-actions[bot]"
      #     user_email: "github-actions[bot]@users.noreply.github.com"
